### ISSUE TITLE
Issues pulling Historical Alerts via API

### ISSUE THREAD

**Issue by dustinbeare** [kentik/community_sdk_python#102]
I've found several other issues with the Historical alerts API:

1)  If there is an alert that was triggered in the requested timeframe which was deleted, and therefore has an alert policy which no longer exists, the script will crash and not work.

2)   I had to modify the following SDK files in order to properly define the HistoricalAlert and _HistoricalAlert classes: 

/kentik_api/public/manual_mitigation.py
class HistoricalAlert:
    alert_value2nd: float
    alert_value3rd: float
  

/kentik_api/request_payload/manual_mitigations_payload.py
class _HistoricalAlert:
    alert_metric: List
    alert_value2nd: float
    alert_value3rd: float

3) I had to modify the following file as well so that a filter_value of None wasn't sent, which was also breaking the script:
/kentik_api/api_calls/alerts.py
@get
def get_alerts_history(
    start_time: str,
    end_time: str,
    filter_by: str,
    filter_val: str,
    sort_order: Optional[str],
    show_mitigations: int,
    show_alarms: int,
    show_matches: int,
    learning_mode: int,
) -> APICall:
    """Returns active alerts (alarms)."""
    return APICall(
        f"/alerts-active/alerts-history?startTime={start_time}&endTime={end_time}&filterBy={filter_by}&"
        f"filterVal=&sortOrder={sort_order}&showMitigations={show_mitigations}&showAlarms={show_alarms}&"
        f"showMatches={show_matches}&learningMode={learning_mode}"

I think #3 may be working now, as I haven't tested the new push yet, but number 1 and 2 still exist.

**Comment by mmac-m3a** [comment]
Fix was released in version v0.3.2.
