### ISSUE TITLE
add HTTP "User-Agent" header at the calls to Kentik API

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/community_sdk_python#126]
add HTTP "User-Agent" header at the calls to Kentik API, with the values of `kentik_community_sdk_python/<version>`

**Comment by mmac-m3a** [comment]
Passing of requests HTTP header (and gRPC request meta-data) has been implemented in [PR#129](https://github.com/kentik/community_sdk_python/pull/129) and will be released on version 1.0.0 soon.
