### ISSUE TITLE
Default filterVal=None causes 500 error for alerting history API call

### ISSUE THREAD

**Issue by dustinbeare** [kentik/community_sdk_python#98]
The default value for the filterVal when calling the get_alerts_history() API call is set to None in https://github.com/kentik/community_sdk_python/blob/main/kentik_api_library/kentik_api/api_resources/alerting_api.py

When no filterBy or filterVal is passed in this call, and only a start and end time are passed into it, the response is 'too many 500 error responses):

API Error HTTPSConnectionPool(host='api.kentik.com', port=443): Max retries exceeded with url: /api/v5/alerts-active/alerts-history?startTime=2021-12-01T00:00:00&endTime=2021-12-15T00:00:00&filterBy=None&filterVal=None&sortOrder=None&showMitigations=1&showAlarms=1&showMatches=0&learningMode=0 (Caused by ResponseError('too many 500 error responses'))

However, if the same call above is made with filterVal= or filterVal left off altogether, the response is the correct information:

curl --location --request GET 'https://api.kentik.com/api/v5/alerts-active/alerts-history?startTime=2021-12-01T00:00:00&endTime=2021-12-15T00:00:00&filterBy=None&filterVal=&showMitigations=1&showAlarms=1&showMatches=0&learningMode=0'

**Comment by Fenthick** [comment]
Bug fix has been merged to _main_ branch: https://github.com/kentik/community_sdk_python/pull/99

**Comment by mmac-m3a** [comment]
Fix was released in version v0.3.2.
